services:
  frontend:
    image: react_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - rails_app