export const fakeEventsData = [
  {
    id: "1",
    label: "Event 1 & 4:00 - 5:00",
    groupLabel: "Event",
    user: "Admin",
    startHour: "04:00 AM",
    endHour: "05:00 AM",
    date: "2024-01-17",
    location: "A",
    description: "",
  },
  {
    id: "2",
    label: "Event 2  & 9:00 - 10:00",
    groupLabel: "Event",
    user: "Admin",
    startHour: "09:00 AM",
    endHour: "10:00 AM",
    date: "2024-01-17",
    location: "A",
    description: "",
  },
  {
    id: "3",
    label: "Event 3  & 13:00 - 14:00",
    groupLabel: "Event",
    user: "Admin",
    startHour: "13:00 PM",
    endHour: "14:00 PM",
    date: "2024-01-17",
    location: "A",
    description: "",
  },
];
export const upcomingEvent = [
  {
    id: 1,
    name: "Nhung thanh pho mo mang music show",
    duration: "9:00 - 18:00",
    location: "9:00 - 18:00",
    participant: "Gem Ga",
  },
  {
    id: 2,
    name: "Nhung thanh pho mo mang music show",
    duration: "9:00 - 18:00",
    location: "9:00 - 18:00",
    participant: "Gem Ga",
  },
  {
    id: 3,
    name: "Nhung thanh pho mo mang music show",
    duration: "9:00 - 18:00",
    location: "9:00 - 18:00",
    participant: "Dung Ngu",
  },
  {
    id: 4,
    name: "Nhung thanh pho mo mang music show",
    duration: "9:00 - 18:00",
    location: "9:00 - 18:00",
    participant: "Dung Ngu",
  },
  {
    id: 5,
    name: "Nhung thanh pho mo mang music show",
    duration: "Lunchbox 9:00 - 18:00",
    location: "Lunchbox 9:00 - 18:00",
    participant: "Dung Ngu",
  },
];
