services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: serverside_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:  # This should be inside 'services'
    build: .
    container_name: rails_app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://user:password@db:5432/serverside_development
      RAILS_ENV: production
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:3000:3000"
      - "0.0.0.0:3421:3421"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"

volumes:
  postgres_data:
